# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'TPKeyboardAvoiding', '~> 1.3'
	pod 'MBProgressHUD', '~> 1.0'

  # Pods for TestApp

end
